// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/LibModels/CalendarEventDM.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DataModel {

  /// <summary>Holder for reflection information generated from Protos/LibModels/CalendarEventDM.proto</summary>
  public static partial class CalendarEventDMReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/LibModels/CalendarEventDM.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CalendarEventDMReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiZQcm90b3MvTGliTW9kZWxzL0NhbGVuZGFyRXZlbnRETS5wcm90bxIJRGF0",
            "YU1vZGVsGhVQcm90b3MvQ29tbW9uRG0ucHJvdG8="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DataModel.CommonDmReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
