// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/LibModels/MsgDM.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DataModel {

  /// <summary>Holder for reflection information generated from Protos/LibModels/MsgDM.proto</summary>
  public static partial class MsgDMReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/LibModels/MsgDM.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MsgDMReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxQcm90b3MvTGliTW9kZWxzL01zZ0RNLnByb3RvEglEYXRhTW9kZWwaFVBy",
            "b3Rvcy9Db21tb25EbS5wcm90bxogUHJvdG9zL0xpYk1vZGVscy9BY2NvdW50",
            "RE0ucHJvdG8i0gEKBU1zZ0RNEgoKAklEGAEgAigJEiEKBHR5cGUYAiACKA4y",
            "Ey5EYXRhTW9kZWwuRU1zZ1R5cGUSDAoEdGltZRgDIAIoAxIMCgRyZWFkGAUg",
            "AigIEjMKD3NBY2NvdW50Q2FzY2FkZRgGIAIoCzIaLkRhdGFNb2RlbC5TaW1w",
            "bGVBY2NvdW50RE0SDQoFdGl0bGUYCiACKAkSDwoHY29udGVudBgLIAEoCRIp",
            "CgtsaW5rQ2FzY2FkZRgPIAEoCzIULkRhdGFNb2RlbC5Nc2dMaW5rRE0iNgoJ",
            "TXNnTGlua0RNEgsKA3VybBgBIAIoCRIOCgZ1cmxQaWMYAiABKAkSDAoEZGVz",
            "YxgDIAIoCSJ5CgdNc2dJbmZvEh8KBWluZm9zGAEgAygLMhAuRGF0YU1vZGVs",
            "Lk1zZ0RNIhcKClByb3RvTW9kSUQSCQoFTW9kSUQQAiIXCgpQcm90b0Z1bklE",
            "EgkKBUZ1bklEEAEiGwoOUHJvdG9Sb3V0ZURlc3QSCQoFUm91dGUQACpkCghF",
            "TXNnVHlwZRILCgdBbnlUeXBlEAASEAoMTm90aWZpY2F0aW9uEAESDAoIQ2Fs",
            "ZW5kYXIQAhIJCgVMb2NhbBAEEgkKBEluZm8QgAESCQoEV2FybhCAAhIKCgVF",
            "cnJvchCABA=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DataModel.CommonDmReflection.Descriptor, global::DataModel.AccountDMReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::DataModel.EMsgType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DataModel.MsgDM), global::DataModel.MsgDM.Parser, new[]{ "ID", "Type", "Time", "Read", "SAccountCascade", "Title", "Content", "LinkCascade" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DataModel.MsgLinkDM), global::DataModel.MsgLinkDM.Parser, new[]{ "Url", "UrlPic", "Desc" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DataModel.MsgInfo), global::DataModel.MsgInfo.Parser, new[]{ "Infos" }, null, new[]{ typeof(global::DataModel.MsgInfo.Types.ProtoModID), typeof(global::DataModel.MsgInfo.Types.ProtoFunID), typeof(global::DataModel.MsgInfo.Types.ProtoRouteDest) }, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum EMsgType {
    [pbr::OriginalName("AnyType")] AnyType = 0,
    /// <summary>
    /// 通知 泛指服务器端发到客户端的通知
    /// </summary>
    [pbr::OriginalName("Notification")] Notification = 1,
    /// <summary>
    /// 日历事件
    /// </summary>
    [pbr::OriginalName("Calendar")] Calendar = 2,
    /// <summary>
    /// 本地事件
    /// </summary>
    [pbr::OriginalName("Local")] Local = 4,
    /// <summary>
    /// 严重程度
    /// </summary>
    [pbr::OriginalName("Info")] Info = 128,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("Warn")] Warn = 256,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("Error")] Error = 512,
  }

  #endregion

  #region Messages
  public sealed partial class MsgDM : pb::IMessage<MsgDM>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MsgDM> _parser = new pb::MessageParser<MsgDM>(() => new MsgDM());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MsgDM> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DataModel.MsgDMReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgDM() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgDM(MsgDM other) : this() {
      _hasBits0 = other._hasBits0;
      iD_ = other.iD_;
      type_ = other.type_;
      time_ = other.time_;
      read_ = other.read_;
      sAccountCascade_ = other.sAccountCascade_ != null ? other.sAccountCascade_.Clone() : null;
      title_ = other.title_;
      content_ = other.content_;
      linkCascade_ = other.linkCascade_ != null ? other.linkCascade_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgDM Clone() {
      return new MsgDM(this);
    }

    /// <summary>Field number for the "ID" field.</summary>
    public const int IDFieldNumber = 1;
    private readonly static string IDDefaultValue = "";

    private string iD_;
    /// <summary>
    ///ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ID {
      get { return iD_ ?? IDDefaultValue; }
      set {
        iD_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "ID" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasID {
      get { return iD_ != null; }
    }
    /// <summary>Clears the value of the "ID" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearID() {
      iD_ = null;
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 2;
    private readonly static global::DataModel.EMsgType TypeDefaultValue = global::DataModel.EMsgType.AnyType;

    private global::DataModel.EMsgType type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DataModel.EMsgType Type {
      get { if ((_hasBits0 & 1) != 0) { return type_; } else { return TypeDefaultValue; } }
      set {
        _hasBits0 |= 1;
        type_ = value;
      }
    }
    /// <summary>Gets whether the "type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasType {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "type" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearType() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 3;
    private readonly static long TimeDefaultValue = 0L;

    private long time_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Time {
      get { if ((_hasBits0 & 2) != 0) { return time_; } else { return TimeDefaultValue; } }
      set {
        _hasBits0 |= 2;
        time_ = value;
      }
    }
    /// <summary>Gets whether the "time" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasTime {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "time" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearTime() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "read" field.</summary>
    public const int ReadFieldNumber = 5;
    private readonly static bool ReadDefaultValue = false;

    private bool read_;
    /// <summary>
    /// 是否已读
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Read {
      get { if ((_hasBits0 & 4) != 0) { return read_; } else { return ReadDefaultValue; } }
      set {
        _hasBits0 |= 4;
        read_ = value;
      }
    }
    /// <summary>Gets whether the "read" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasRead {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "read" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearRead() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "sAccountCascade" field.</summary>
    public const int SAccountCascadeFieldNumber = 6;
    private global::DataModel.SimpleAccountDM sAccountCascade_;
    /// <summary>
    ///    required string         fromAccName     = 7;
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DataModel.SimpleAccountDM SAccountCascade {
      get { return sAccountCascade_; }
      set {
        sAccountCascade_ = value;
      }
    }

    /// <summary>Field number for the "title" field.</summary>
    public const int TitleFieldNumber = 10;
    private readonly static string TitleDefaultValue = "";

    private string title_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Title {
      get { return title_ ?? TitleDefaultValue; }
      set {
        title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "title" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasTitle {
      get { return title_ != null; }
    }
    /// <summary>Clears the value of the "title" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearTitle() {
      title_ = null;
    }

    /// <summary>Field number for the "content" field.</summary>
    public const int ContentFieldNumber = 11;
    private readonly static string ContentDefaultValue = "";

    private string content_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Content {
      get { return content_ ?? ContentDefaultValue; }
      set {
        content_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "content" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasContent {
      get { return content_ != null; }
    }
    /// <summary>Clears the value of the "content" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearContent() {
      content_ = null;
    }

    /// <summary>Field number for the "linkCascade" field.</summary>
    public const int LinkCascadeFieldNumber = 15;
    private global::DataModel.MsgLinkDM linkCascade_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DataModel.MsgLinkDM LinkCascade {
      get { return linkCascade_; }
      set {
        linkCascade_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MsgDM);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MsgDM other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ID != other.ID) return false;
      if (Type != other.Type) return false;
      if (Time != other.Time) return false;
      if (Read != other.Read) return false;
      if (!object.Equals(SAccountCascade, other.SAccountCascade)) return false;
      if (Title != other.Title) return false;
      if (Content != other.Content) return false;
      if (!object.Equals(LinkCascade, other.LinkCascade)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasID) hash ^= ID.GetHashCode();
      if (HasType) hash ^= Type.GetHashCode();
      if (HasTime) hash ^= Time.GetHashCode();
      if (HasRead) hash ^= Read.GetHashCode();
      if (sAccountCascade_ != null) hash ^= SAccountCascade.GetHashCode();
      if (HasTitle) hash ^= Title.GetHashCode();
      if (HasContent) hash ^= Content.GetHashCode();
      if (linkCascade_ != null) hash ^= LinkCascade.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasID) {
        output.WriteRawTag(10);
        output.WriteString(ID);
      }
      if (HasType) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (HasTime) {
        output.WriteRawTag(24);
        output.WriteInt64(Time);
      }
      if (HasRead) {
        output.WriteRawTag(40);
        output.WriteBool(Read);
      }
      if (sAccountCascade_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(SAccountCascade);
      }
      if (HasTitle) {
        output.WriteRawTag(82);
        output.WriteString(Title);
      }
      if (HasContent) {
        output.WriteRawTag(90);
        output.WriteString(Content);
      }
      if (linkCascade_ != null) {
        output.WriteRawTag(122);
        output.WriteMessage(LinkCascade);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasID) {
        output.WriteRawTag(10);
        output.WriteString(ID);
      }
      if (HasType) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (HasTime) {
        output.WriteRawTag(24);
        output.WriteInt64(Time);
      }
      if (HasRead) {
        output.WriteRawTag(40);
        output.WriteBool(Read);
      }
      if (sAccountCascade_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(SAccountCascade);
      }
      if (HasTitle) {
        output.WriteRawTag(82);
        output.WriteString(Title);
      }
      if (HasContent) {
        output.WriteRawTag(90);
        output.WriteString(Content);
      }
      if (linkCascade_ != null) {
        output.WriteRawTag(122);
        output.WriteMessage(LinkCascade);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasID) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ID);
      }
      if (HasType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (HasTime) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Time);
      }
      if (HasRead) {
        size += 1 + 1;
      }
      if (sAccountCascade_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SAccountCascade);
      }
      if (HasTitle) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
      }
      if (HasContent) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Content);
      }
      if (linkCascade_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LinkCascade);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MsgDM other) {
      if (other == null) {
        return;
      }
      if (other.HasID) {
        ID = other.ID;
      }
      if (other.HasType) {
        Type = other.Type;
      }
      if (other.HasTime) {
        Time = other.Time;
      }
      if (other.HasRead) {
        Read = other.Read;
      }
      if (other.sAccountCascade_ != null) {
        if (sAccountCascade_ == null) {
          SAccountCascade = new global::DataModel.SimpleAccountDM();
        }
        SAccountCascade.MergeFrom(other.SAccountCascade);
      }
      if (other.HasTitle) {
        Title = other.Title;
      }
      if (other.HasContent) {
        Content = other.Content;
      }
      if (other.linkCascade_ != null) {
        if (linkCascade_ == null) {
          LinkCascade = new global::DataModel.MsgLinkDM();
        }
        LinkCascade.MergeFrom(other.LinkCascade);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ID = input.ReadString();
            break;
          }
          case 16: {
            Type = (global::DataModel.EMsgType) input.ReadEnum();
            break;
          }
          case 24: {
            Time = input.ReadInt64();
            break;
          }
          case 40: {
            Read = input.ReadBool();
            break;
          }
          case 50: {
            if (sAccountCascade_ == null) {
              SAccountCascade = new global::DataModel.SimpleAccountDM();
            }
            input.ReadMessage(SAccountCascade);
            break;
          }
          case 82: {
            Title = input.ReadString();
            break;
          }
          case 90: {
            Content = input.ReadString();
            break;
          }
          case 122: {
            if (linkCascade_ == null) {
              LinkCascade = new global::DataModel.MsgLinkDM();
            }
            input.ReadMessage(LinkCascade);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ID = input.ReadString();
            break;
          }
          case 16: {
            Type = (global::DataModel.EMsgType) input.ReadEnum();
            break;
          }
          case 24: {
            Time = input.ReadInt64();
            break;
          }
          case 40: {
            Read = input.ReadBool();
            break;
          }
          case 50: {
            if (sAccountCascade_ == null) {
              SAccountCascade = new global::DataModel.SimpleAccountDM();
            }
            input.ReadMessage(SAccountCascade);
            break;
          }
          case 82: {
            Title = input.ReadString();
            break;
          }
          case 90: {
            Content = input.ReadString();
            break;
          }
          case 122: {
            if (linkCascade_ == null) {
              LinkCascade = new global::DataModel.MsgLinkDM();
            }
            input.ReadMessage(LinkCascade);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class MsgLinkDM : pb::IMessage<MsgLinkDM>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MsgLinkDM> _parser = new pb::MessageParser<MsgLinkDM>(() => new MsgLinkDM());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MsgLinkDM> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DataModel.MsgDMReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgLinkDM() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgLinkDM(MsgLinkDM other) : this() {
      url_ = other.url_;
      urlPic_ = other.urlPic_;
      desc_ = other.desc_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgLinkDM Clone() {
      return new MsgLinkDM(this);
    }

    /// <summary>Field number for the "url" field.</summary>
    public const int UrlFieldNumber = 1;
    private readonly static string UrlDefaultValue = "";

    private string url_;
    /// <summary>
    /// URl
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Url {
      get { return url_ ?? UrlDefaultValue; }
      set {
        url_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "url" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasUrl {
      get { return url_ != null; }
    }
    /// <summary>Clears the value of the "url" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearUrl() {
      url_ = null;
    }

    /// <summary>Field number for the "urlPic" field.</summary>
    public const int UrlPicFieldNumber = 2;
    private readonly static string UrlPicDefaultValue = "";

    private string urlPic_;
    /// <summary>
    /// pic 也是URl表示
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UrlPic {
      get { return urlPic_ ?? UrlPicDefaultValue; }
      set {
        urlPic_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "urlPic" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasUrlPic {
      get { return urlPic_ != null; }
    }
    /// <summary>Clears the value of the "urlPic" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearUrlPic() {
      urlPic_ = null;
    }

    /// <summary>Field number for the "desc" field.</summary>
    public const int DescFieldNumber = 3;
    private readonly static string DescDefaultValue = "";

    private string desc_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Desc {
      get { return desc_ ?? DescDefaultValue; }
      set {
        desc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "desc" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasDesc {
      get { return desc_ != null; }
    }
    /// <summary>Clears the value of the "desc" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearDesc() {
      desc_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MsgLinkDM);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MsgLinkDM other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Url != other.Url) return false;
      if (UrlPic != other.UrlPic) return false;
      if (Desc != other.Desc) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasUrl) hash ^= Url.GetHashCode();
      if (HasUrlPic) hash ^= UrlPic.GetHashCode();
      if (HasDesc) hash ^= Desc.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasUrl) {
        output.WriteRawTag(10);
        output.WriteString(Url);
      }
      if (HasUrlPic) {
        output.WriteRawTag(18);
        output.WriteString(UrlPic);
      }
      if (HasDesc) {
        output.WriteRawTag(26);
        output.WriteString(Desc);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasUrl) {
        output.WriteRawTag(10);
        output.WriteString(Url);
      }
      if (HasUrlPic) {
        output.WriteRawTag(18);
        output.WriteString(UrlPic);
      }
      if (HasDesc) {
        output.WriteRawTag(26);
        output.WriteString(Desc);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasUrl) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Url);
      }
      if (HasUrlPic) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UrlPic);
      }
      if (HasDesc) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Desc);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MsgLinkDM other) {
      if (other == null) {
        return;
      }
      if (other.HasUrl) {
        Url = other.Url;
      }
      if (other.HasUrlPic) {
        UrlPic = other.UrlPic;
      }
      if (other.HasDesc) {
        Desc = other.Desc;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Url = input.ReadString();
            break;
          }
          case 18: {
            UrlPic = input.ReadString();
            break;
          }
          case 26: {
            Desc = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Url = input.ReadString();
            break;
          }
          case 18: {
            UrlPic = input.ReadString();
            break;
          }
          case 26: {
            Desc = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class MsgInfo : pb::IMessage<MsgInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MsgInfo> _parser = new pb::MessageParser<MsgInfo>(() => new MsgInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MsgInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DataModel.MsgDMReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgInfo(MsgInfo other) : this() {
      infos_ = other.infos_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgInfo Clone() {
      return new MsgInfo(this);
    }

    /// <summary>Field number for the "infos" field.</summary>
    public const int InfosFieldNumber = 1;
    private static readonly pb::FieldCodec<global::DataModel.MsgDM> _repeated_infos_codec
        = pb::FieldCodec.ForMessage(10, global::DataModel.MsgDM.Parser);
    private readonly pbc::RepeatedField<global::DataModel.MsgDM> infos_ = new pbc::RepeatedField<global::DataModel.MsgDM>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::DataModel.MsgDM> Infos {
      get { return infos_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MsgInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MsgInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!infos_.Equals(other.infos_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= infos_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      infos_.WriteTo(output, _repeated_infos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      infos_.WriteTo(ref output, _repeated_infos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += infos_.CalculateSize(_repeated_infos_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MsgInfo other) {
      if (other == null) {
        return;
      }
      infos_.Add(other.infos_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            infos_.AddEntriesFrom(input, _repeated_infos_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            infos_.AddEntriesFrom(ref input, _repeated_infos_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the MsgInfo message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum ProtoModID {
        [pbr::OriginalName("ModID")] ModId = 2,
      }

      public enum ProtoFunID {
        [pbr::OriginalName("FunID")] FunId = 1,
      }

      public enum ProtoRouteDest {
        [pbr::OriginalName("Route")] Route = 0,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
