/********************************************************************
    created:	2019/11/27 19:51:29
    author:		rush
    email:		
	
    purpose:	地区  包含
*********************************************************************/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RLib.Base
{
    public enum ECity                   // 城
    {
        None,
        北京,
        天津,
        石家庄,
        唐山,
        秦皇岛,
        邯郸,
        邢台,
        保定,
        张家口,
        承德,
        沧州,
        廊坊,
        衡水,
        太原,
        大同,
        阳泉,
        长治,
        晋城,
        朔州,
        晋中,
        运城,
        忻州,
        临汾,
        吕梁,
        呼和浩特,
        包头,
        乌海,
        赤峰,
        通辽,
        鄂尔多斯,
        呼伦贝尔,
        巴彦淖尔,
        乌兰察布,
        兴安盟,
        锡林郭勒盟,
        阿拉善盟,
        沈阳,
        大连,
        鞍山,
        抚顺,
        本溪,
        丹东,
        锦州,
        营口,
        阜新,
        辽阳,
        盘锦,
        铁岭,
        朝阳,
        葫芦岛,
        长春,
        吉林,
        四平,
        辽源,
        通化,
        白山,
        松原,
        白城,
        延边朝鲜族自治州,
        哈尔滨,
        齐齐哈尔,
        鸡西,
        鹤岗,
        双鸭山,
        大庆,
        伊春,
        佳木斯,
        七台河,
        牡丹江,
        黑河,
        绥化,
        大兴安岭地区,
        上海,
        南京,
        无锡,
        徐州,
        常州,
        苏州,
        南通,
        连云港,
        淮安,
        盐城,
        扬州,
        镇江,
        泰州,
        宿迁,
        杭州,
        宁波,
        温州,
        嘉兴,
        湖州,
        绍兴,
        金华,
        衢州,
        舟山,
        台州,
        丽水,
        合肥,
        芜湖,
        蚌埠,
        淮南,
        马鞍山,
        淮北,
        铜陵,
        安庆,
        黄山,
        滁州,
        阜阳,
        宿州,
        巢湖,
        六安,
        亳州,
        池州,
        宣城,
        福州,
        厦门,
        莆田,
        三明,
        泉州,
        漳州,
        南平,
        龙岩,
        宁德,
        南昌,
        景德镇,
        萍乡,
        九江,
        新余,
        鹰潭,
        赣州,
        吉安,
        宜春,
        抚州,
        上饶,
        济南,
        青岛,
        淄博,
        枣庄,
        东营,
        烟台,
        潍坊,
        济宁,
        泰安,
        威海,
        日照,
        莱芜,
        临沂,
        德州,
        聊城,
        滨州,
        荷泽,
        郑州,
        开封,
        洛阳,
        平顶山,
        安阳,
        鹤壁,
        新乡,
        焦作,
        濮阳,
        许昌,
        漯河,
        三门峡,
        南阳,
        商丘,
        信阳,
        周口,
        驻马店,
        武汉,
        黄石,
        十堰,
        宜昌,
        襄樊,
        鄂州,
        荆门,
        孝感,
        荆州,
        黄冈,
        咸宁,
        随州,
        恩施土家族苗族自治州,
        神农架,
        长沙,
        株洲,
        湘潭,
        衡阳,
        邵阳,
        岳阳,
        常德,
        张家界,
        益阳,
        郴州,
        永州,
        怀化,
        娄底,
        湘西土家族苗族自治州,
        广州,
        韶关,
        深圳,
        珠海,
        汕头,
        佛山,
        江门,
        湛江,
        茂名,
        肇庆,
        惠州,
        梅州,
        汕尾,
        河源,
        阳江,
        清远,
        东莞,
        中山,
        潮州,
        揭阳,
        云浮,
        南宁,
        柳州,
        桂林,
        梧州,
        北海,
        防城港,
        钦州,
        贵港,
        玉林,
        百色,
        贺州,
        河池,
        来宾,
        崇左,
        海口,
        三亚,
        重庆,
        成都,
        自贡,
        攀枝花,
        泸州,
        德阳,
        绵阳,
        广元,
        遂宁,
        内江,
        乐山,
        南充,
        眉山,
        宜宾,
        广安,
        达州,
        雅安,
        巴中,
        资阳,
        阿坝藏族羌族自治州,
        甘孜藏族自治州,
        凉山彝族自治州,
        贵阳,
        六盘水,
        遵义,
        安顺,
        铜仁地区,
        黔西南布依族苗族自治州,
        毕节地区,
        黔东南苗族侗族自治州,
        黔南布依族苗族自治州,
        昆明,
        曲靖,
        玉溪,
        保山,
        昭通,
        丽江,
        思茅,
        临沧,
        楚雄彝族自治州,
        红河哈尼族彝族自治州,
        文山壮族苗族自治州,
        西双版纳傣族自治州,
        大理白族自治州,
        德宏傣族景颇族自治州,
        怒江傈僳族自治州,
        迪庆藏族自治州,
        拉萨,
        昌都地区,
        山南地区,
        日喀则地区,
        那曲地区,
        阿里地区,
        林芝地区,
        西安,
        铜川,
        宝鸡,
        咸阳,
        渭南,
        延安,
        汉中,
        榆林,
        安康,
        商洛,
        兰州,
        嘉峪关,
        金昌,
        白银,
        天水,
        武威,
        张掖,
        平凉,
        酒泉,
        庆阳,
        定西,
        陇南,
        临夏回族自治州,
        甘南藏族自治州,
        西宁,
        海东地区,
        海北藏族自治州,
        黄南藏族自治州,
        海南藏族自治州,
        果洛藏族自治州,
        玉树藏族自治州,
        海西蒙古族藏族自治州,
        银川,
        石嘴山,
        吴忠,
        固原,
        中卫,
        乌鲁木齐,
        克拉玛依,
        吐鲁番地区,
        哈密地区,
        昌吉回族自治州,
        博尔塔拉蒙古自治州,
        巴音郭楞蒙古自治州,
        阿克苏地区,
        克孜勒苏柯尔克孜自治州,
        喀什地区,
        和田地区,
        伊犁哈萨克自治州,
        塔城地区,
        阿勒泰地区,
        石河子,
        阿拉尔,
        图木舒克,
        五家渠,
        香港特别行政区,
        澳门特别行政区,
        台湾,
    }

    public enum EProvince                   // 城
    {
        None,
        北京,
        天津,
        河北,
        山西,
        内蒙古自治区,
        辽宁,
        吉林,
        黑龙江,
        上海,
        江苏,
        浙江,
        安徽,
        福建,
        江西,
        山东,
        河南,
        湖北,
        湖南,
        广东,
        广西壮族自治区,
        海南,
        重庆,
        四川,
        贵州,
        云南,
        西藏自治区,
        陕西,
        甘肃,
        青海,
        宁夏回族自治区,
        新疆维吾尔自治区,
        香港特别行政区,
        澳门特别行政区,
        台湾,     
    }

    public static class City
    {
        public static List<EProvince> GetAllProvinces()
        {
            return Enum.GetValues(typeof(EProvince)).OfType<EProvince>().ToList();
        }

        public static EProvince GetProvince(this ECity city)
        {
            if (city != ECity.None)
                return Cities.First(p => p.Item2 == city).Item1;
            else
                return EProvince.None;
        }

        public static List<ECity> GetCities(this EProvince province)
        {
            if(province!= EProvince.None)
                return Cities.Where(p => p.Item1 == province).Select(p=>p.Item2).ToList();
            else 
                return new List<ECity>(){ECity.None};
        }

        public static List<ECity> GetCities(string province)
        {
            return Cities.Where(p => p.Item1.ToString() == province).Select(p => p.Item2).ToList();
        }




        public static ECity ToCity(this string city)
        {
            ECity ret;
            if (Enum.TryParse(city, out ret))
                return ret;
            else
                return ECity.None;
        }

        public static EProvince? ToProvince(this string province)
        {
            EProvince ret;
            if (Enum.TryParse(province, out ret))
                return ret;
            else
                return null;
        }

        public static int GetZipCode(this ECity city)
        {
            return Cities.First(p => p.Item2 == city).Item3;
        }

        public static List<Tuple<EProvince, ECity, int>> Cities = new List<Tuple<EProvince, ECity, int>>()
        {
            new Tuple<EProvince, ECity, int>(EProvince.北京, ECity.北京,100000),
            new Tuple<EProvince, ECity, int>(EProvince.天津, ECity.天津,300000),
            new Tuple<EProvince, ECity, int>(EProvince.河北, ECity.石家庄,050000),
            new Tuple<EProvince, ECity, int>(EProvince.河北, ECity.唐山,063000),
            new Tuple<EProvince, ECity, int>(EProvince.河北, ECity.秦皇岛,066000),
            new Tuple<EProvince, ECity, int>(EProvince.河北, ECity.邯郸,056000),
            new Tuple<EProvince, ECity, int>(EProvince.河北, ECity.邢台,054000),
            new Tuple<EProvince, ECity, int>(EProvince.河北, ECity.保定,071000),
            new Tuple<EProvince, ECity, int>(EProvince.河北, ECity.张家口,075000),
            new Tuple<EProvince, ECity, int>(EProvince.河北, ECity.承德,067000),
            new Tuple<EProvince, ECity, int>(EProvince.河北, ECity.沧州,061000),
            new Tuple<EProvince, ECity, int>(EProvince.河北, ECity.廊坊,065000),
            new Tuple<EProvince, ECity, int>(EProvince.河北, ECity.衡水,053000),
            new Tuple<EProvince, ECity, int>(EProvince.山西, ECity.太原,030000),
            new Tuple<EProvince, ECity, int>(EProvince.山西, ECity.大同,037000),
            new Tuple<EProvince, ECity, int>(EProvince.山西, ECity.阳泉,045000),
            new Tuple<EProvince, ECity, int>(EProvince.山西, ECity.长治,046000),
            new Tuple<EProvince, ECity, int>(EProvince.山西, ECity.晋城,048000),
            new Tuple<EProvince, ECity, int>(EProvince.山西, ECity.朔州,036000),
            new Tuple<EProvince, ECity, int>(EProvince.山西, ECity.晋中,030600),
            new Tuple<EProvince, ECity, int>(EProvince.山西, ECity.运城,044000),
            new Tuple<EProvince, ECity, int>(EProvince.山西, ECity.忻州,034000),
            new Tuple<EProvince, ECity, int>(EProvince.山西, ECity.临汾,041000),
            new Tuple<EProvince, ECity, int>(EProvince.山西, ECity.吕梁,030500),
            new Tuple<EProvince, ECity, int>(EProvince.内蒙古自治区, ECity.呼和浩特,010000),
            new Tuple<EProvince, ECity, int>(EProvince.内蒙古自治区, ECity.包头,014000),
            new Tuple<EProvince, ECity, int>(EProvince.内蒙古自治区, ECity.乌海,016000),
            new Tuple<EProvince, ECity, int>(EProvince.内蒙古自治区, ECity.赤峰,024000),
            new Tuple<EProvince, ECity, int>(EProvince.内蒙古自治区, ECity.通辽,028000),
            new Tuple<EProvince, ECity, int>(EProvince.内蒙古自治区, ECity.鄂尔多斯,010300),
            new Tuple<EProvince, ECity, int>(EProvince.内蒙古自治区, ECity.呼伦贝尔,021000),
            new Tuple<EProvince, ECity, int>(EProvince.内蒙古自治区, ECity.巴彦淖尔,014400),
            new Tuple<EProvince, ECity, int>(EProvince.内蒙古自治区, ECity.乌兰察布,011800),
            new Tuple<EProvince, ECity, int>(EProvince.内蒙古自治区, ECity.兴安盟,137500),
            new Tuple<EProvince, ECity, int>(EProvince.内蒙古自治区, ECity.锡林郭勒盟,011100),
            new Tuple<EProvince, ECity, int>(EProvince.内蒙古自治区, ECity.阿拉善盟,016000),
            new Tuple<EProvince, ECity, int>(EProvince.辽宁, ECity.沈阳,110000),
            new Tuple<EProvince, ECity, int>(EProvince.辽宁, ECity.大连,116000),
            new Tuple<EProvince, ECity, int>(EProvince.辽宁, ECity.鞍山,114000),
            new Tuple<EProvince, ECity, int>(EProvince.辽宁, ECity.抚顺,113000),
            new Tuple<EProvince, ECity, int>(EProvince.辽宁, ECity.本溪,117000),
            new Tuple<EProvince, ECity, int>(EProvince.辽宁, ECity.丹东,118000),
            new Tuple<EProvince, ECity, int>(EProvince.辽宁, ECity.锦州,121000),
            new Tuple<EProvince, ECity, int>(EProvince.辽宁, ECity.营口,115000),
            new Tuple<EProvince, ECity, int>(EProvince.辽宁, ECity.阜新,123000),
            new Tuple<EProvince, ECity, int>(EProvince.辽宁, ECity.辽阳,111000),
            new Tuple<EProvince, ECity, int>(EProvince.辽宁, ECity.盘锦,124000),
            new Tuple<EProvince, ECity, int>(EProvince.辽宁, ECity.铁岭,112000),
            new Tuple<EProvince, ECity, int>(EProvince.辽宁, ECity.朝阳,122000),
            new Tuple<EProvince, ECity, int>(EProvince.辽宁, ECity.葫芦岛,125000),
            new Tuple<EProvince, ECity, int>(EProvince.吉林, ECity.长春,130000),
            new Tuple<EProvince, ECity, int>(EProvince.吉林, ECity.吉林,132000),
            new Tuple<EProvince, ECity, int>(EProvince.吉林, ECity.四平,136000),
            new Tuple<EProvince, ECity, int>(EProvince.吉林, ECity.辽源,136200),
            new Tuple<EProvince, ECity, int>(EProvince.吉林, ECity.通化,134000),
            new Tuple<EProvince, ECity, int>(EProvince.吉林, ECity.白山,134300),
            new Tuple<EProvince, ECity, int>(EProvince.吉林, ECity.松原,131100),
            new Tuple<EProvince, ECity, int>(EProvince.吉林, ECity.白城,137000),
            new Tuple<EProvince, ECity, int>(EProvince.吉林, ECity.延边朝鲜族自治州,133000),
            new Tuple<EProvince, ECity, int>(EProvince.黑龙江, ECity.哈尔滨,150000),
            new Tuple<EProvince, ECity, int>(EProvince.黑龙江, ECity.齐齐哈尔,161000),
            new Tuple<EProvince, ECity, int>(EProvince.黑龙江, ECity.鸡西,158100),
            new Tuple<EProvince, ECity, int>(EProvince.黑龙江, ECity.鹤岗,154100),
            new Tuple<EProvince, ECity, int>(EProvince.黑龙江, ECity.双鸭山,155100),
            new Tuple<EProvince, ECity, int>(EProvince.黑龙江, ECity.大庆,163000),
            new Tuple<EProvince, ECity, int>(EProvince.黑龙江, ECity.伊春,152300),
            new Tuple<EProvince, ECity, int>(EProvince.黑龙江, ECity.佳木斯,154000),
            new Tuple<EProvince, ECity, int>(EProvince.黑龙江, ECity.七台河,154600),
            new Tuple<EProvince, ECity, int>(EProvince.黑龙江, ECity.牡丹江,157000),
            new Tuple<EProvince, ECity, int>(EProvince.黑龙江, ECity.黑河,164300),
            new Tuple<EProvince, ECity, int>(EProvince.黑龙江, ECity.绥化,152000),
            new Tuple<EProvince, ECity, int>(EProvince.黑龙江, ECity.大兴安岭地区,165000),
            new Tuple<EProvince, ECity, int>(EProvince.上海, ECity.上海,200000),
            new Tuple<EProvince, ECity, int>(EProvince.江苏, ECity.南京,210000),
            new Tuple<EProvince, ECity, int>(EProvince.江苏, ECity.无锡,214000),
            new Tuple<EProvince, ECity, int>(EProvince.江苏, ECity.徐州,221000),
            new Tuple<EProvince, ECity, int>(EProvince.江苏, ECity.常州,213000),
            new Tuple<EProvince, ECity, int>(EProvince.江苏, ECity.苏州,215000),
            new Tuple<EProvince, ECity, int>(EProvince.江苏, ECity.南通,226000),
            new Tuple<EProvince, ECity, int>(EProvince.江苏, ECity.连云港,222000),
            new Tuple<EProvince, ECity, int>(EProvince.江苏, ECity.淮安,223200),
            new Tuple<EProvince, ECity, int>(EProvince.江苏, ECity.盐城,224000),
            new Tuple<EProvince, ECity, int>(EProvince.江苏, ECity.扬州,225000),
            new Tuple<EProvince, ECity, int>(EProvince.江苏, ECity.镇江,212000),
            new Tuple<EProvince, ECity, int>(EProvince.江苏, ECity.泰州,225300),
            new Tuple<EProvince, ECity, int>(EProvince.江苏, ECity.宿迁,223800),
            new Tuple<EProvince, ECity, int>(EProvince.浙江, ECity.杭州,310000),
            new Tuple<EProvince, ECity, int>(EProvince.浙江, ECity.宁波,315000),
            new Tuple<EProvince, ECity, int>(EProvince.浙江, ECity.温州,325000),
            new Tuple<EProvince, ECity, int>(EProvince.浙江, ECity.嘉兴,314000),
            new Tuple<EProvince, ECity, int>(EProvince.浙江, ECity.湖州,313000),
            new Tuple<EProvince, ECity, int>(EProvince.浙江, ECity.绍兴,312000),
            new Tuple<EProvince, ECity, int>(EProvince.浙江, ECity.金华,321000),
            new Tuple<EProvince, ECity, int>(EProvince.浙江, ECity.衢州,324000),
            new Tuple<EProvince, ECity, int>(EProvince.浙江, ECity.舟山,316000),
            new Tuple<EProvince, ECity, int>(EProvince.浙江, ECity.台州,318000),
            new Tuple<EProvince, ECity, int>(EProvince.浙江, ECity.丽水,323000),
            new Tuple<EProvince, ECity, int>(EProvince.安徽, ECity.合肥,230000),
            new Tuple<EProvince, ECity, int>(EProvince.安徽, ECity.芜湖,241000),
            new Tuple<EProvince, ECity, int>(EProvince.安徽, ECity.蚌埠,233000),
            new Tuple<EProvince, ECity, int>(EProvince.安徽, ECity.淮南,232000),
            new Tuple<EProvince, ECity, int>(EProvince.安徽, ECity.马鞍山,243000),
            new Tuple<EProvince, ECity, int>(EProvince.安徽, ECity.淮北,235000),
            new Tuple<EProvince, ECity, int>(EProvince.安徽, ECity.铜陵,244000),
            new Tuple<EProvince, ECity, int>(EProvince.安徽, ECity.安庆,246000),
            new Tuple<EProvince, ECity, int>(EProvince.安徽, ECity.黄山,242700),
            new Tuple<EProvince, ECity, int>(EProvince.安徽, ECity.滁州,239000),
            new Tuple<EProvince, ECity, int>(EProvince.安徽, ECity.阜阳,236100),
            new Tuple<EProvince, ECity, int>(EProvince.安徽, ECity.宿州,234100),
            new Tuple<EProvince, ECity, int>(EProvince.安徽, ECity.巢湖,238000),
            new Tuple<EProvince, ECity, int>(EProvince.安徽, ECity.六安,237000),
            new Tuple<EProvince, ECity, int>(EProvince.安徽, ECity.亳州,236800),
            new Tuple<EProvince, ECity, int>(EProvince.安徽, ECity.池州,247100),
            new Tuple<EProvince, ECity, int>(EProvince.安徽, ECity.宣城,366000),
            new Tuple<EProvince, ECity, int>(EProvince.福建, ECity.福州,350000),
            new Tuple<EProvince, ECity, int>(EProvince.福建, ECity.厦门,361000),
            new Tuple<EProvince, ECity, int>(EProvince.福建, ECity.莆田,351100),
            new Tuple<EProvince, ECity, int>(EProvince.福建, ECity.三明,365000),
            new Tuple<EProvince, ECity, int>(EProvince.福建, ECity.泉州,362000),
            new Tuple<EProvince, ECity, int>(EProvince.福建, ECity.漳州,363000),
            new Tuple<EProvince, ECity, int>(EProvince.福建, ECity.南平,353000),
            new Tuple<EProvince, ECity, int>(EProvince.福建, ECity.龙岩,364000),
            new Tuple<EProvince, ECity, int>(EProvince.福建, ECity.宁德,352100),
            new Tuple<EProvince, ECity, int>(EProvince.江西, ECity.南昌,330000),
            new Tuple<EProvince, ECity, int>(EProvince.江西, ECity.景德镇,333000),
            new Tuple<EProvince, ECity, int>(EProvince.江西, ECity.萍乡,337000),
            new Tuple<EProvince, ECity, int>(EProvince.江西, ECity.九江,332000),
            new Tuple<EProvince, ECity, int>(EProvince.江西, ECity.新余,338000),
            new Tuple<EProvince, ECity, int>(EProvince.江西, ECity.鹰潭,335000),
            new Tuple<EProvince, ECity, int>(EProvince.江西, ECity.赣州,341000),
            new Tuple<EProvince, ECity, int>(EProvince.江西, ECity.吉安,343000),
            new Tuple<EProvince, ECity, int>(EProvince.江西, ECity.宜春,336000),
            new Tuple<EProvince, ECity, int>(EProvince.江西, ECity.抚州,332900),
            new Tuple<EProvince, ECity, int>(EProvince.江西, ECity.上饶,334000),
            new Tuple<EProvince, ECity, int>(EProvince.山东, ECity.济南,250000),
            new Tuple<EProvince, ECity, int>(EProvince.山东, ECity.青岛,266000),
            new Tuple<EProvince, ECity, int>(EProvince.山东, ECity.淄博,255000),
            new Tuple<EProvince, ECity, int>(EProvince.山东, ECity.枣庄,277100),
            new Tuple<EProvince, ECity, int>(EProvince.山东, ECity.东营,257000),
            new Tuple<EProvince, ECity, int>(EProvince.山东, ECity.烟台,264000),
            new Tuple<EProvince, ECity, int>(EProvince.山东, ECity.潍坊,261000),
            new Tuple<EProvince, ECity, int>(EProvince.山东, ECity.济宁,272100),
            new Tuple<EProvince, ECity, int>(EProvince.山东, ECity.泰安,271000),
            new Tuple<EProvince, ECity, int>(EProvince.山东, ECity.威海,265700),
            new Tuple<EProvince, ECity, int>(EProvince.山东, ECity.日照,276800),
            new Tuple<EProvince, ECity, int>(EProvince.山东, ECity.莱芜,271100),
            new Tuple<EProvince, ECity, int>(EProvince.山东, ECity.临沂,276000),
            new Tuple<EProvince, ECity, int>(EProvince.山东, ECity.德州,253000),
            new Tuple<EProvince, ECity, int>(EProvince.山东, ECity.聊城,252000),
            new Tuple<EProvince, ECity, int>(EProvince.山东, ECity.滨州,256600),
            new Tuple<EProvince, ECity, int>(EProvince.山东, ECity.荷泽,255000),
            new Tuple<EProvince, ECity, int>(EProvince.河南, ECity.郑州,450000),
            new Tuple<EProvince, ECity, int>(EProvince.河南, ECity.开封,475000),
            new Tuple<EProvince, ECity, int>(EProvince.河南, ECity.洛阳,471000),
            new Tuple<EProvince, ECity, int>(EProvince.河南, ECity.平顶山,467000),
            new Tuple<EProvince, ECity, int>(EProvince.河南, ECity.安阳,454900),
            new Tuple<EProvince, ECity, int>(EProvince.河南, ECity.鹤壁,456600),
            new Tuple<EProvince, ECity, int>(EProvince.河南, ECity.新乡,453000),
            new Tuple<EProvince, ECity, int>(EProvince.河南, ECity.焦作,454100),
            new Tuple<EProvince, ECity, int>(EProvince.河南, ECity.濮阳,457000),
            new Tuple<EProvince, ECity, int>(EProvince.河南, ECity.许昌,461000),
            new Tuple<EProvince, ECity, int>(EProvince.河南, ECity.漯河,462000),
            new Tuple<EProvince, ECity, int>(EProvince.河南, ECity.三门峡,472000),
            new Tuple<EProvince, ECity, int>(EProvince.河南, ECity.南阳,473000),
            new Tuple<EProvince, ECity, int>(EProvince.河南, ECity.商丘,476000),
            new Tuple<EProvince, ECity, int>(EProvince.河南, ECity.信阳,464000),
            new Tuple<EProvince, ECity, int>(EProvince.河南, ECity.周口,466000),
            new Tuple<EProvince, ECity, int>(EProvince.河南, ECity.驻马店,463000),
            new Tuple<EProvince, ECity, int>(EProvince.湖北, ECity.武汉,430000),
            new Tuple<EProvince, ECity, int>(EProvince.湖北, ECity.黄石,435000),
            new Tuple<EProvince, ECity, int>(EProvince.湖北, ECity.十堰,442000),
            new Tuple<EProvince, ECity, int>(EProvince.湖北, ECity.宜昌,443000),
            new Tuple<EProvince, ECity, int>(EProvince.湖北, ECity.襄樊,441000),
            new Tuple<EProvince, ECity, int>(EProvince.湖北, ECity.鄂州,436000),
            new Tuple<EProvince, ECity, int>(EProvince.湖北, ECity.荆门,448000),
            new Tuple<EProvince, ECity, int>(EProvince.湖北, ECity.孝感,432100),
            new Tuple<EProvince, ECity, int>(EProvince.湖北, ECity.荆州,434000),
            new Tuple<EProvince, ECity, int>(EProvince.湖北, ECity.黄冈,438000),
            new Tuple<EProvince, ECity, int>(EProvince.湖北, ECity.咸宁,437000),
            new Tuple<EProvince, ECity, int>(EProvince.湖北, ECity.随州,441300),
            new Tuple<EProvince, ECity, int>(EProvince.湖北, ECity.恩施土家族苗族自治州,445000),
            new Tuple<EProvince, ECity, int>(EProvince.湖北, ECity.神农架,442400),
            new Tuple<EProvince, ECity, int>(EProvince.湖南, ECity.长沙,410000),
            new Tuple<EProvince, ECity, int>(EProvince.湖南, ECity.株洲,412000),
            new Tuple<EProvince, ECity, int>(EProvince.湖南, ECity.湘潭,411100),
            new Tuple<EProvince, ECity, int>(EProvince.湖南, ECity.衡阳,421000),
            new Tuple<EProvince, ECity, int>(EProvince.湖南, ECity.邵阳,422000),
            new Tuple<EProvince, ECity, int>(EProvince.湖南, ECity.岳阳,414000),
            new Tuple<EProvince, ECity, int>(EProvince.湖南, ECity.常德,415000),
            new Tuple<EProvince, ECity, int>(EProvince.湖南, ECity.张家界,427000),
            new Tuple<EProvince, ECity, int>(EProvince.湖南, ECity.益阳,413000),
            new Tuple<EProvince, ECity, int>(EProvince.湖南, ECity.郴州,423000),
            new Tuple<EProvince, ECity, int>(EProvince.湖南, ECity.永州,425000),
            new Tuple<EProvince, ECity, int>(EProvince.湖南, ECity.怀化,418000),
            new Tuple<EProvince, ECity, int>(EProvince.湖南, ECity.娄底,417000),
            new Tuple<EProvince, ECity, int>(EProvince.湖南, ECity.湘西土家族苗族自治州,416000),
            new Tuple<EProvince, ECity, int>(EProvince.广东, ECity.广州,510000),
            new Tuple<EProvince, ECity, int>(EProvince.广东, ECity.韶关,521000),
            new Tuple<EProvince, ECity, int>(EProvince.广东, ECity.深圳,518000),
            new Tuple<EProvince, ECity, int>(EProvince.广东, ECity.珠海,519000),
            new Tuple<EProvince, ECity, int>(EProvince.广东, ECity.汕头,515000),
            new Tuple<EProvince, ECity, int>(EProvince.广东, ECity.佛山,528000),
            new Tuple<EProvince, ECity, int>(EProvince.广东, ECity.江门,529000),
            new Tuple<EProvince, ECity, int>(EProvince.广东, ECity.湛江,524000),
            new Tuple<EProvince, ECity, int>(EProvince.广东, ECity.茂名,525000),
            new Tuple<EProvince, ECity, int>(EProvince.广东, ECity.肇庆,526000),
            new Tuple<EProvince, ECity, int>(EProvince.广东, ECity.惠州,516000),
            new Tuple<EProvince, ECity, int>(EProvince.广东, ECity.梅州,514000),
            new Tuple<EProvince, ECity, int>(EProvince.广东, ECity.汕尾,516600),
            new Tuple<EProvince, ECity, int>(EProvince.广东, ECity.河源,517000),
            new Tuple<EProvince, ECity, int>(EProvince.广东, ECity.阳江,529500),
            new Tuple<EProvince, ECity, int>(EProvince.广东, ECity.清远,511500),
            new Tuple<EProvince, ECity, int>(EProvince.广东, ECity.东莞,511700),
            new Tuple<EProvince, ECity, int>(EProvince.广东, ECity.中山,528400),
            new Tuple<EProvince, ECity, int>(EProvince.广东, ECity.潮州,515600),
            new Tuple<EProvince, ECity, int>(EProvince.广东, ECity.揭阳,522000),
            new Tuple<EProvince, ECity, int>(EProvince.广东, ECity.云浮,527300),
            new Tuple<EProvince, ECity, int>(EProvince.广西壮族自治区, ECity.南宁,530000),
            new Tuple<EProvince, ECity, int>(EProvince.广西壮族自治区, ECity.柳州,545000),
            new Tuple<EProvince, ECity, int>(EProvince.广西壮族自治区, ECity.桂林,541000),
            new Tuple<EProvince, ECity, int>(EProvince.广西壮族自治区, ECity.梧州,543000),
            new Tuple<EProvince, ECity, int>(EProvince.广西壮族自治区, ECity.北海,536000),
            new Tuple<EProvince, ECity, int>(EProvince.广西壮族自治区, ECity.防城港,538000),
            new Tuple<EProvince, ECity, int>(EProvince.广西壮族自治区, ECity.钦州,535000),
            new Tuple<EProvince, ECity, int>(EProvince.广西壮族自治区, ECity.贵港,537100),
            new Tuple<EProvince, ECity, int>(EProvince.广西壮族自治区, ECity.玉林,537000),
            new Tuple<EProvince, ECity, int>(EProvince.广西壮族自治区, ECity.百色,533000),
            new Tuple<EProvince, ECity, int>(EProvince.广西壮族自治区, ECity.贺州,542800),
            new Tuple<EProvince, ECity, int>(EProvince.广西壮族自治区, ECity.河池,547000),
            new Tuple<EProvince, ECity, int>(EProvince.广西壮族自治区, ECity.来宾,546100),
            new Tuple<EProvince, ECity, int>(EProvince.广西壮族自治区, ECity.崇左,532200),
            new Tuple<EProvince, ECity, int>(EProvince.海南, ECity.海口,570000),
            new Tuple<EProvince, ECity, int>(EProvince.海南, ECity.三亚,572000),
            new Tuple<EProvince, ECity, int>(EProvince.重庆, ECity.重庆,400000),
            new Tuple<EProvince, ECity, int>(EProvince.四川, ECity.成都,610000),
            new Tuple<EProvince, ECity, int>(EProvince.四川, ECity.自贡,643000),
            new Tuple<EProvince, ECity, int>(EProvince.四川, ECity.攀枝花,617000),
            new Tuple<EProvince, ECity, int>(EProvince.四川, ECity.泸州,646100),
            new Tuple<EProvince, ECity, int>(EProvince.四川, ECity.德阳,618000),
            new Tuple<EProvince, ECity, int>(EProvince.四川, ECity.绵阳,621000),
            new Tuple<EProvince, ECity, int>(EProvince.四川, ECity.广元,628000),
            new Tuple<EProvince, ECity, int>(EProvince.四川, ECity.遂宁,629000),
            new Tuple<EProvince, ECity, int>(EProvince.四川, ECity.内江,641000),
            new Tuple<EProvince, ECity, int>(EProvince.四川, ECity.乐山,614000),
            new Tuple<EProvince, ECity, int>(EProvince.四川, ECity.南充,637000),
            new Tuple<EProvince, ECity, int>(EProvince.四川, ECity.眉山,612100),
            new Tuple<EProvince, ECity, int>(EProvince.四川, ECity.宜宾,644000),
            new Tuple<EProvince, ECity, int>(EProvince.四川, ECity.广安,638000),
            new Tuple<EProvince, ECity, int>(EProvince.四川, ECity.达州,635000),
            new Tuple<EProvince, ECity, int>(EProvince.四川, ECity.雅安,625000),
            new Tuple<EProvince, ECity, int>(EProvince.四川, ECity.巴中,635500),
            new Tuple<EProvince, ECity, int>(EProvince.四川, ECity.资阳,641300),
            new Tuple<EProvince, ECity, int>(EProvince.四川, ECity.阿坝藏族羌族自治州,624600),
            new Tuple<EProvince, ECity, int>(EProvince.四川, ECity.甘孜藏族自治州,626000),
            new Tuple<EProvince, ECity, int>(EProvince.四川, ECity.凉山彝族自治州,615000),
            new Tuple<EProvince, ECity, int>(EProvince.贵州, ECity.贵阳,55000),
            new Tuple<EProvince, ECity, int>(EProvince.贵州, ECity.六盘水,553000),
            new Tuple<EProvince, ECity, int>(EProvince.贵州, ECity.遵义,563000),
            new Tuple<EProvince, ECity, int>(EProvince.贵州, ECity.安顺,561000),
            new Tuple<EProvince, ECity, int>(EProvince.贵州, ECity.铜仁地区,554300),
            new Tuple<EProvince, ECity, int>(EProvince.贵州, ECity.黔西南布依族苗族自治州,551500),
            new Tuple<EProvince, ECity, int>(EProvince.贵州, ECity.毕节地区,551700),
            new Tuple<EProvince, ECity, int>(EProvince.贵州, ECity.黔东南苗族侗族自治州,551500),
            new Tuple<EProvince, ECity, int>(EProvince.贵州, ECity.黔南布依族苗族自治州,550100),
            new Tuple<EProvince, ECity, int>(EProvince.云南, ECity.昆明,650000),
            new Tuple<EProvince, ECity, int>(EProvince.云南, ECity.曲靖,655000),
            new Tuple<EProvince, ECity, int>(EProvince.云南, ECity.玉溪,653100),
            new Tuple<EProvince, ECity, int>(EProvince.云南, ECity.保山,678000),
            new Tuple<EProvince, ECity, int>(EProvince.云南, ECity.昭通,657000),
            new Tuple<EProvince, ECity, int>(EProvince.云南, ECity.丽江,674100),
            new Tuple<EProvince, ECity, int>(EProvince.云南, ECity.思茅,665000),
            new Tuple<EProvince, ECity, int>(EProvince.云南, ECity.临沧,677000),
            new Tuple<EProvince, ECity, int>(EProvince.云南, ECity.楚雄彝族自治州,675000),
            new Tuple<EProvince, ECity, int>(EProvince.云南, ECity.红河哈尼族彝族自治州,654400),
            new Tuple<EProvince, ECity, int>(EProvince.云南, ECity.文山壮族苗族自治州,663000),
            new Tuple<EProvince, ECity, int>(EProvince.云南, ECity.西双版纳傣族自治州,666200),
            new Tuple<EProvince, ECity, int>(EProvince.云南, ECity.大理白族自治州,671000),
            new Tuple<EProvince, ECity, int>(EProvince.云南, ECity.德宏傣族景颇族自治州,678400),
            new Tuple<EProvince, ECity, int>(EProvince.云南, ECity.怒江傈僳族自治州,671400),
            new Tuple<EProvince, ECity, int>(EProvince.云南, ECity.迪庆藏族自治州,674400),
            new Tuple<EProvince, ECity, int>(EProvince.西藏自治区, ECity.拉萨,850000),
            new Tuple<EProvince, ECity, int>(EProvince.西藏自治区, ECity.昌都地区,854000),
            new Tuple<EProvince, ECity, int>(EProvince.西藏自治区, ECity.山南地区,856000),
            new Tuple<EProvince, ECity, int>(EProvince.西藏自治区, ECity.日喀则地区,857000),
            new Tuple<EProvince, ECity, int>(EProvince.西藏自治区, ECity.那曲地区,852000),
            new Tuple<EProvince, ECity, int>(EProvince.西藏自治区, ECity.阿里地区,859100),
            new Tuple<EProvince, ECity, int>(EProvince.西藏自治区, ECity.林芝地区,860100),
            new Tuple<EProvince, ECity, int>(EProvince.陕西, ECity.西安,710000),
            new Tuple<EProvince, ECity, int>(EProvince.陕西, ECity.铜川,727000),
            new Tuple<EProvince, ECity, int>(EProvince.陕西, ECity.宝鸡,721000),
            new Tuple<EProvince, ECity, int>(EProvince.陕西, ECity.咸阳,712000),
            new Tuple<EProvince, ECity, int>(EProvince.陕西, ECity.渭南,714000),
            new Tuple<EProvince, ECity, int>(EProvince.陕西, ECity.延安,716000),
            new Tuple<EProvince, ECity, int>(EProvince.陕西, ECity.汉中,723000),
            new Tuple<EProvince, ECity, int>(EProvince.陕西, ECity.榆林,719000),
            new Tuple<EProvince, ECity, int>(EProvince.陕西, ECity.安康,725000),
            new Tuple<EProvince, ECity, int>(EProvince.陕西, ECity.商洛,711500),
            new Tuple<EProvince, ECity, int>(EProvince.甘肃, ECity.兰州,730000),
            new Tuple<EProvince, ECity, int>(EProvince.甘肃, ECity.嘉峪关,735100),
            new Tuple<EProvince, ECity, int>(EProvince.甘肃, ECity.金昌,737100),
            new Tuple<EProvince, ECity, int>(EProvince.甘肃, ECity.白银,730900),
            new Tuple<EProvince, ECity, int>(EProvince.甘肃, ECity.天水,741000),
            new Tuple<EProvince, ECity, int>(EProvince.甘肃, ECity.武威,733000),
            new Tuple<EProvince, ECity, int>(EProvince.甘肃, ECity.张掖,734000),
            new Tuple<EProvince, ECity, int>(EProvince.甘肃, ECity.平凉,744000),
            new Tuple<EProvince, ECity, int>(EProvince.甘肃, ECity.酒泉,735000),
            new Tuple<EProvince, ECity, int>(EProvince.甘肃, ECity.庆阳,744500),
            new Tuple<EProvince, ECity, int>(EProvince.甘肃, ECity.定西,743000),
            new Tuple<EProvince, ECity, int>(EProvince.甘肃, ECity.陇南,742100),
            new Tuple<EProvince, ECity, int>(EProvince.甘肃, ECity.临夏回族自治州,731100),
            new Tuple<EProvince, ECity, int>(EProvince.甘肃, ECity.甘南藏族自治州,747000),
            new Tuple<EProvince, ECity, int>(EProvince.青海, ECity.西宁,810000),
            new Tuple<EProvince, ECity, int>(EProvince.青海, ECity.海东地区,810600),
            new Tuple<EProvince, ECity, int>(EProvince.青海, ECity.海北藏族自治州,810300),
            new Tuple<EProvince, ECity, int>(EProvince.青海, ECity.黄南藏族自治州,811300),
            new Tuple<EProvince, ECity, int>(EProvince.青海, ECity.海南藏族自治州,813000),
            new Tuple<EProvince, ECity, int>(EProvince.青海, ECity.果洛藏族自治州,814000),
            new Tuple<EProvince, ECity, int>(EProvince.青海, ECity.玉树藏族自治州,815000),
            new Tuple<EProvince, ECity, int>(EProvince.青海, ECity.海西蒙古族藏族自治州,817000),
            new Tuple<EProvince, ECity, int>(EProvince.宁夏回族自治区, ECity.银川,750000),
            new Tuple<EProvince, ECity, int>(EProvince.宁夏回族自治区, ECity.石嘴山,753000),
            new Tuple<EProvince, ECity, int>(EProvince.宁夏回族自治区, ECity.吴忠,751100),
            new Tuple<EProvince, ECity, int>(EProvince.宁夏回族自治区, ECity.固原,756000),
            new Tuple<EProvince, ECity, int>(EProvince.宁夏回族自治区, ECity.中卫,751700),
            new Tuple<EProvince, ECity, int>(EProvince.新疆维吾尔自治区, ECity.乌鲁木齐,830000),
            new Tuple<EProvince, ECity, int>(EProvince.新疆维吾尔自治区, ECity.克拉玛依,834000),
            new Tuple<EProvince, ECity, int>(EProvince.新疆维吾尔自治区, ECity.吐鲁番地区,838000),
            new Tuple<EProvince, ECity, int>(EProvince.新疆维吾尔自治区, ECity.哈密地区,839000),
            new Tuple<EProvince, ECity, int>(EProvince.新疆维吾尔自治区, ECity.昌吉回族自治州,831100),
            new Tuple<EProvince, ECity, int>(EProvince.新疆维吾尔自治区, ECity.博尔塔拉蒙古自治州,833400),
            new Tuple<EProvince, ECity, int>(EProvince.新疆维吾尔自治区, ECity.巴音郭楞蒙古自治州,841000),
            new Tuple<EProvince, ECity, int>(EProvince.新疆维吾尔自治区, ECity.阿克苏地区,843000),
            new Tuple<EProvince, ECity, int>(EProvince.新疆维吾尔自治区, ECity.克孜勒苏柯尔克孜自治州,835600),
            new Tuple<EProvince, ECity, int>(EProvince.新疆维吾尔自治区, ECity.喀什地区,844000),
            new Tuple<EProvince, ECity, int>(EProvince.新疆维吾尔自治区, ECity.和田地区,848000),
            new Tuple<EProvince, ECity, int>(EProvince.新疆维吾尔自治区, ECity.伊犁哈萨克自治州,833200),
            new Tuple<EProvince, ECity, int>(EProvince.新疆维吾尔自治区, ECity.塔城地区,834700),
            new Tuple<EProvince, ECity, int>(EProvince.新疆维吾尔自治区, ECity.阿勒泰地区,836500),
            new Tuple<EProvince, ECity, int>(EProvince.新疆维吾尔自治区, ECity.石河子,832000),
            new Tuple<EProvince, ECity, int>(EProvince.新疆维吾尔自治区, ECity.阿拉尔,843300),
            new Tuple<EProvince, ECity, int>(EProvince.新疆维吾尔自治区, ECity.图木舒克,843900),
            new Tuple<EProvince, ECity, int>(EProvince.新疆维吾尔自治区, ECity.五家渠,831300),
            new Tuple<EProvince, ECity, int>(EProvince.香港特别行政区, ECity.香港特别行政区,999077),
            new Tuple<EProvince, ECity, int>(EProvince.澳门特别行政区, ECity.澳门特别行政区,999078),
            new Tuple<EProvince, ECity, int>(EProvince.台湾, ECity.台湾,00000),

        };

    }
}
