// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/Neo/MarketData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DataModel {

  /// <summary>Holder for reflection information generated from Protos/Neo/MarketData.proto</summary>
  public static partial class MarketDataReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/Neo/MarketData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MarketDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtQcm90b3MvTmVvL01hcmtldERhdGEucHJvdG8SCURhdGFNb2RlbBofZ29v",
            "Z2xlL3Byb3RvYnVmL3RpbWVzdGFtcC5wcm90bxoVUHJvdG9zL0NvbW1vbkRt",
            "LnByb3RvGhpQcm90b3MvTmVvL05lb0NvbW1vbi5wcm90byI8CgpQcmljZUVu",
            "dHJ5Eg0KBVByaWNlGAEgAigBEgwKBFNpemUYAiABKA0SEQoJT3JkZXJzTnVt",
            "GAMgASgNIpMBCgZUaWNrRE0SCgoCSWQYASACKAQSEgoKU2VjdXJpdHlJZBgC",
            "IAIoBBIOCgZTeW1ib2wYAyABKAkSKAoEVGltZRgEIAIoCzIaLmdvb2dsZS5w",
            "cm90b2J1Zi5UaW1lc3RhbXASDQoFUHJpY2UYBSACKAESDgoGVm9sdW1lGAYg",
            "ASgBEhAKCFR1cm5vdmVyGAcgASgBIvcBCgVCYXJETRIKCgJJZBgBIAIoBBIS",
            "CgpTZWN1cml0eUlkGAIgAigEEg4KBlN5bWJvbBgDIAEoCRIoCglUaW1lRnJh",
            "bWUYBCACKA4yFS5EYXRhTW9kZWwuRVRpbWVGcmFtZRIoCgRUaW1lGAUgAigL",
            "MhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIMCgRPcGVuGAogAigBEgwK",
            "BEhpZ2gYCyACKAESCwoDTG93GAwgAigBEg0KBUNsb3NlGA0gAigBEhAKCFBy",
            "ZWNsb3NlGA4gASgBEg4KBlZvbHVtZRgPIAEoARIQCghUdXJub3ZlchgQIAEo",
            "AQ=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::DataModel.CommonDmReflection.Descriptor, global::DataModel.NeoCommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DataModel.PriceEntry), global::DataModel.PriceEntry.Parser, new[]{ "Price", "Size", "OrdersNum" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DataModel.TickDM), global::DataModel.TickDM.Parser, new[]{ "Id", "SecurityId", "Symbol", "Time", "Price", "Volume", "Turnover" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DataModel.BarDM), global::DataModel.BarDM.Parser, new[]{ "Id", "SecurityId", "Symbol", "TimeFrame", "Time", "Open", "High", "Low", "Close", "Preclose", "Volume", "Turnover" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PriceEntry : pb::IMessage<PriceEntry>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PriceEntry> _parser = new pb::MessageParser<PriceEntry>(() => new PriceEntry());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PriceEntry> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DataModel.MarketDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PriceEntry() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PriceEntry(PriceEntry other) : this() {
      _hasBits0 = other._hasBits0;
      price_ = other.price_;
      size_ = other.size_;
      ordersNum_ = other.ordersNum_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PriceEntry Clone() {
      return new PriceEntry(this);
    }

    /// <summary>Field number for the "Price" field.</summary>
    public const int PriceFieldNumber = 1;
    private readonly static double PriceDefaultValue = 0D;

    private double price_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Price {
      get { if ((_hasBits0 & 1) != 0) { return price_; } else { return PriceDefaultValue; } }
      set {
        _hasBits0 |= 1;
        price_ = value;
      }
    }
    /// <summary>Gets whether the "Price" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasPrice {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "Price" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearPrice() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "Size" field.</summary>
    public const int SizeFieldNumber = 2;
    private readonly static uint SizeDefaultValue = 0;

    private uint size_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Size {
      get { if ((_hasBits0 & 2) != 0) { return size_; } else { return SizeDefaultValue; } }
      set {
        _hasBits0 |= 2;
        size_ = value;
      }
    }
    /// <summary>Gets whether the "Size" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasSize {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "Size" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearSize() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "OrdersNum" field.</summary>
    public const int OrdersNumFieldNumber = 3;
    private readonly static uint OrdersNumDefaultValue = 0;

    private uint ordersNum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint OrdersNum {
      get { if ((_hasBits0 & 4) != 0) { return ordersNum_; } else { return OrdersNumDefaultValue; } }
      set {
        _hasBits0 |= 4;
        ordersNum_ = value;
      }
    }
    /// <summary>Gets whether the "OrdersNum" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasOrdersNum {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "OrdersNum" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearOrdersNum() {
      _hasBits0 &= ~4;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PriceEntry);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PriceEntry other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Price, other.Price)) return false;
      if (Size != other.Size) return false;
      if (OrdersNum != other.OrdersNum) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasPrice) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Price);
      if (HasSize) hash ^= Size.GetHashCode();
      if (HasOrdersNum) hash ^= OrdersNum.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasPrice) {
        output.WriteRawTag(9);
        output.WriteDouble(Price);
      }
      if (HasSize) {
        output.WriteRawTag(16);
        output.WriteUInt32(Size);
      }
      if (HasOrdersNum) {
        output.WriteRawTag(24);
        output.WriteUInt32(OrdersNum);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasPrice) {
        output.WriteRawTag(9);
        output.WriteDouble(Price);
      }
      if (HasSize) {
        output.WriteRawTag(16);
        output.WriteUInt32(Size);
      }
      if (HasOrdersNum) {
        output.WriteRawTag(24);
        output.WriteUInt32(OrdersNum);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasPrice) {
        size += 1 + 8;
      }
      if (HasSize) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Size);
      }
      if (HasOrdersNum) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(OrdersNum);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PriceEntry other) {
      if (other == null) {
        return;
      }
      if (other.HasPrice) {
        Price = other.Price;
      }
      if (other.HasSize) {
        Size = other.Size;
      }
      if (other.HasOrdersNum) {
        OrdersNum = other.OrdersNum;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            Price = input.ReadDouble();
            break;
          }
          case 16: {
            Size = input.ReadUInt32();
            break;
          }
          case 24: {
            OrdersNum = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            Price = input.ReadDouble();
            break;
          }
          case 16: {
            Size = input.ReadUInt32();
            break;
          }
          case 24: {
            OrdersNum = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// ¼òµ¥tick
  /// </summary>
  public sealed partial class TickDM : pb::IMessage<TickDM>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TickDM> _parser = new pb::MessageParser<TickDM>(() => new TickDM());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TickDM> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DataModel.MarketDataReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TickDM() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TickDM(TickDM other) : this() {
      _hasBits0 = other._hasBits0;
      id_ = other.id_;
      securityId_ = other.securityId_;
      symbol_ = other.symbol_;
      time_ = other.time_ != null ? other.time_.Clone() : null;
      price_ = other.price_;
      volume_ = other.volume_;
      turnover_ = other.turnover_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TickDM Clone() {
      return new TickDM(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private readonly static ulong IdDefaultValue = 0UL;

    private ulong id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Id {
      get { if ((_hasBits0 & 1) != 0) { return id_; } else { return IdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        id_ = value;
      }
    }
    /// <summary>Gets whether the "Id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "Id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "SecurityId" field.</summary>
    public const int SecurityIdFieldNumber = 2;
    private readonly static ulong SecurityIdDefaultValue = 0UL;

    private ulong securityId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong SecurityId {
      get { if ((_hasBits0 & 2) != 0) { return securityId_; } else { return SecurityIdDefaultValue; } }
      set {
        _hasBits0 |= 2;
        securityId_ = value;
      }
    }
    /// <summary>Gets whether the "SecurityId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasSecurityId {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "SecurityId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearSecurityId() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "Symbol" field.</summary>
    public const int SymbolFieldNumber = 3;
    private readonly static string SymbolDefaultValue = "";

    private string symbol_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Symbol {
      get { return symbol_ ?? SymbolDefaultValue; }
      set {
        symbol_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "Symbol" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasSymbol {
      get { return symbol_ != null; }
    }
    /// <summary>Clears the value of the "Symbol" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearSymbol() {
      symbol_ = null;
    }

    /// <summary>Field number for the "Time" field.</summary>
    public const int TimeFieldNumber = 4;
    private global::Google.Protobuf.WellKnownTypes.Timestamp time_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    /// <summary>Field number for the "Price" field.</summary>
    public const int PriceFieldNumber = 5;
    private readonly static double PriceDefaultValue = 0D;

    private double price_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Price {
      get { if ((_hasBits0 & 4) != 0) { return price_; } else { return PriceDefaultValue; } }
      set {
        _hasBits0 |= 4;
        price_ = value;
      }
    }
    /// <summary>Gets whether the "Price" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasPrice {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "Price" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearPrice() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "Volume" field.</summary>
    public const int VolumeFieldNumber = 6;
    private readonly static double VolumeDefaultValue = 0D;

    private double volume_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Volume {
      get { if ((_hasBits0 & 8) != 0) { return volume_; } else { return VolumeDefaultValue; } }
      set {
        _hasBits0 |= 8;
        volume_ = value;
      }
    }
    /// <summary>Gets whether the "Volume" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasVolume {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "Volume" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearVolume() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "Turnover" field.</summary>
    public const int TurnoverFieldNumber = 7;
    private readonly static double TurnoverDefaultValue = 0D;

    private double turnover_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Turnover {
      get { if ((_hasBits0 & 16) != 0) { return turnover_; } else { return TurnoverDefaultValue; } }
      set {
        _hasBits0 |= 16;
        turnover_ = value;
      }
    }
    /// <summary>Gets whether the "Turnover" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasTurnover {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "Turnover" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearTurnover() {
      _hasBits0 &= ~16;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TickDM);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TickDM other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (SecurityId != other.SecurityId) return false;
      if (Symbol != other.Symbol) return false;
      if (!object.Equals(Time, other.Time)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Price, other.Price)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Volume, other.Volume)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Turnover, other.Turnover)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasId) hash ^= Id.GetHashCode();
      if (HasSecurityId) hash ^= SecurityId.GetHashCode();
      if (HasSymbol) hash ^= Symbol.GetHashCode();
      if (time_ != null) hash ^= Time.GetHashCode();
      if (HasPrice) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Price);
      if (HasVolume) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Volume);
      if (HasTurnover) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Turnover);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasId) {
        output.WriteRawTag(8);
        output.WriteUInt64(Id);
      }
      if (HasSecurityId) {
        output.WriteRawTag(16);
        output.WriteUInt64(SecurityId);
      }
      if (HasSymbol) {
        output.WriteRawTag(26);
        output.WriteString(Symbol);
      }
      if (time_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Time);
      }
      if (HasPrice) {
        output.WriteRawTag(41);
        output.WriteDouble(Price);
      }
      if (HasVolume) {
        output.WriteRawTag(49);
        output.WriteDouble(Volume);
      }
      if (HasTurnover) {
        output.WriteRawTag(57);
        output.WriteDouble(Turnover);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasId) {
        output.WriteRawTag(8);
        output.WriteUInt64(Id);
      }
      if (HasSecurityId) {
        output.WriteRawTag(16);
        output.WriteUInt64(SecurityId);
      }
      if (HasSymbol) {
        output.WriteRawTag(26);
        output.WriteString(Symbol);
      }
      if (time_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Time);
      }
      if (HasPrice) {
        output.WriteRawTag(41);
        output.WriteDouble(Price);
      }
      if (HasVolume) {
        output.WriteRawTag(49);
        output.WriteDouble(Volume);
      }
      if (HasTurnover) {
        output.WriteRawTag(57);
        output.WriteDouble(Turnover);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Id);
      }
      if (HasSecurityId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(SecurityId);
      }
      if (HasSymbol) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Symbol);
      }
      if (time_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Time);
      }
      if (HasPrice) {
        size += 1 + 8;
      }
      if (HasVolume) {
        size += 1 + 8;
      }
      if (HasTurnover) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TickDM other) {
      if (other == null) {
        return;
      }
      if (other.HasId) {
        Id = other.Id;
      }
      if (other.HasSecurityId) {
        SecurityId = other.SecurityId;
      }
      if (other.HasSymbol) {
        Symbol = other.Symbol;
      }
      if (other.time_ != null) {
        if (time_ == null) {
          Time = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Time.MergeFrom(other.Time);
      }
      if (other.HasPrice) {
        Price = other.Price;
      }
      if (other.HasVolume) {
        Volume = other.Volume;
      }
      if (other.HasTurnover) {
        Turnover = other.Turnover;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadUInt64();
            break;
          }
          case 16: {
            SecurityId = input.ReadUInt64();
            break;
          }
          case 26: {
            Symbol = input.ReadString();
            break;
          }
          case 34: {
            if (time_ == null) {
              Time = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Time);
            break;
          }
          case 41: {
            Price = input.ReadDouble();
            break;
          }
          case 49: {
            Volume = input.ReadDouble();
            break;
          }
          case 57: {
            Turnover = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadUInt64();
            break;
          }
          case 16: {
            SecurityId = input.ReadUInt64();
            break;
          }
          case 26: {
            Symbol = input.ReadString();
            break;
          }
          case 34: {
            if (time_ == null) {
              Time = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Time);
            break;
          }
          case 41: {
            Price = input.ReadDouble();
            break;
          }
          case 49: {
            Volume = input.ReadDouble();
            break;
          }
          case 57: {
            Turnover = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 
  /// </summary>
  public sealed partial class BarDM : pb::IMessage<BarDM>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BarDM> _parser = new pb::MessageParser<BarDM>(() => new BarDM());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BarDM> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DataModel.MarketDataReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BarDM() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BarDM(BarDM other) : this() {
      _hasBits0 = other._hasBits0;
      id_ = other.id_;
      securityId_ = other.securityId_;
      symbol_ = other.symbol_;
      timeFrame_ = other.timeFrame_;
      time_ = other.time_ != null ? other.time_.Clone() : null;
      open_ = other.open_;
      high_ = other.high_;
      low_ = other.low_;
      close_ = other.close_;
      preclose_ = other.preclose_;
      volume_ = other.volume_;
      turnover_ = other.turnover_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BarDM Clone() {
      return new BarDM(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private readonly static ulong IdDefaultValue = 0UL;

    private ulong id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Id {
      get { if ((_hasBits0 & 1) != 0) { return id_; } else { return IdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        id_ = value;
      }
    }
    /// <summary>Gets whether the "Id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "Id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "SecurityId" field.</summary>
    public const int SecurityIdFieldNumber = 2;
    private readonly static ulong SecurityIdDefaultValue = 0UL;

    private ulong securityId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong SecurityId {
      get { if ((_hasBits0 & 2) != 0) { return securityId_; } else { return SecurityIdDefaultValue; } }
      set {
        _hasBits0 |= 2;
        securityId_ = value;
      }
    }
    /// <summary>Gets whether the "SecurityId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasSecurityId {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "SecurityId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearSecurityId() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "Symbol" field.</summary>
    public const int SymbolFieldNumber = 3;
    private readonly static string SymbolDefaultValue = "";

    private string symbol_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Symbol {
      get { return symbol_ ?? SymbolDefaultValue; }
      set {
        symbol_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "Symbol" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasSymbol {
      get { return symbol_ != null; }
    }
    /// <summary>Clears the value of the "Symbol" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearSymbol() {
      symbol_ = null;
    }

    /// <summary>Field number for the "TimeFrame" field.</summary>
    public const int TimeFrameFieldNumber = 4;
    private readonly static global::DataModel.ETimeFrame TimeFrameDefaultValue = global::DataModel.ETimeFrame.None;

    private global::DataModel.ETimeFrame timeFrame_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DataModel.ETimeFrame TimeFrame {
      get { if ((_hasBits0 & 4) != 0) { return timeFrame_; } else { return TimeFrameDefaultValue; } }
      set {
        _hasBits0 |= 4;
        timeFrame_ = value;
      }
    }
    /// <summary>Gets whether the "TimeFrame" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasTimeFrame {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "TimeFrame" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearTimeFrame() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "Time" field.</summary>
    public const int TimeFieldNumber = 5;
    private global::Google.Protobuf.WellKnownTypes.Timestamp time_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    /// <summary>Field number for the "Open" field.</summary>
    public const int OpenFieldNumber = 10;
    private readonly static double OpenDefaultValue = 0D;

    private double open_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Open {
      get { if ((_hasBits0 & 8) != 0) { return open_; } else { return OpenDefaultValue; } }
      set {
        _hasBits0 |= 8;
        open_ = value;
      }
    }
    /// <summary>Gets whether the "Open" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasOpen {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "Open" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearOpen() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "High" field.</summary>
    public const int HighFieldNumber = 11;
    private readonly static double HighDefaultValue = 0D;

    private double high_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double High {
      get { if ((_hasBits0 & 16) != 0) { return high_; } else { return HighDefaultValue; } }
      set {
        _hasBits0 |= 16;
        high_ = value;
      }
    }
    /// <summary>Gets whether the "High" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasHigh {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "High" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearHigh() {
      _hasBits0 &= ~16;
    }

    /// <summary>Field number for the "Low" field.</summary>
    public const int LowFieldNumber = 12;
    private readonly static double LowDefaultValue = 0D;

    private double low_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Low {
      get { if ((_hasBits0 & 32) != 0) { return low_; } else { return LowDefaultValue; } }
      set {
        _hasBits0 |= 32;
        low_ = value;
      }
    }
    /// <summary>Gets whether the "Low" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasLow {
      get { return (_hasBits0 & 32) != 0; }
    }
    /// <summary>Clears the value of the "Low" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearLow() {
      _hasBits0 &= ~32;
    }

    /// <summary>Field number for the "Close" field.</summary>
    public const int CloseFieldNumber = 13;
    private readonly static double CloseDefaultValue = 0D;

    private double close_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Close {
      get { if ((_hasBits0 & 64) != 0) { return close_; } else { return CloseDefaultValue; } }
      set {
        _hasBits0 |= 64;
        close_ = value;
      }
    }
    /// <summary>Gets whether the "Close" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasClose {
      get { return (_hasBits0 & 64) != 0; }
    }
    /// <summary>Clears the value of the "Close" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearClose() {
      _hasBits0 &= ~64;
    }

    /// <summary>Field number for the "Preclose" field.</summary>
    public const int PrecloseFieldNumber = 14;
    private readonly static double PrecloseDefaultValue = 0D;

    private double preclose_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Preclose {
      get { if ((_hasBits0 & 128) != 0) { return preclose_; } else { return PrecloseDefaultValue; } }
      set {
        _hasBits0 |= 128;
        preclose_ = value;
      }
    }
    /// <summary>Gets whether the "Preclose" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasPreclose {
      get { return (_hasBits0 & 128) != 0; }
    }
    /// <summary>Clears the value of the "Preclose" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearPreclose() {
      _hasBits0 &= ~128;
    }

    /// <summary>Field number for the "Volume" field.</summary>
    public const int VolumeFieldNumber = 15;
    private readonly static double VolumeDefaultValue = 0D;

    private double volume_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Volume {
      get { if ((_hasBits0 & 256) != 0) { return volume_; } else { return VolumeDefaultValue; } }
      set {
        _hasBits0 |= 256;
        volume_ = value;
      }
    }
    /// <summary>Gets whether the "Volume" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasVolume {
      get { return (_hasBits0 & 256) != 0; }
    }
    /// <summary>Clears the value of the "Volume" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearVolume() {
      _hasBits0 &= ~256;
    }

    /// <summary>Field number for the "Turnover" field.</summary>
    public const int TurnoverFieldNumber = 16;
    private readonly static double TurnoverDefaultValue = 0D;

    private double turnover_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Turnover {
      get { if ((_hasBits0 & 512) != 0) { return turnover_; } else { return TurnoverDefaultValue; } }
      set {
        _hasBits0 |= 512;
        turnover_ = value;
      }
    }
    /// <summary>Gets whether the "Turnover" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasTurnover {
      get { return (_hasBits0 & 512) != 0; }
    }
    /// <summary>Clears the value of the "Turnover" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearTurnover() {
      _hasBits0 &= ~512;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BarDM);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BarDM other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (SecurityId != other.SecurityId) return false;
      if (Symbol != other.Symbol) return false;
      if (TimeFrame != other.TimeFrame) return false;
      if (!object.Equals(Time, other.Time)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Open, other.Open)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(High, other.High)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Low, other.Low)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Close, other.Close)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Preclose, other.Preclose)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Volume, other.Volume)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Turnover, other.Turnover)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasId) hash ^= Id.GetHashCode();
      if (HasSecurityId) hash ^= SecurityId.GetHashCode();
      if (HasSymbol) hash ^= Symbol.GetHashCode();
      if (HasTimeFrame) hash ^= TimeFrame.GetHashCode();
      if (time_ != null) hash ^= Time.GetHashCode();
      if (HasOpen) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Open);
      if (HasHigh) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(High);
      if (HasLow) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Low);
      if (HasClose) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Close);
      if (HasPreclose) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Preclose);
      if (HasVolume) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Volume);
      if (HasTurnover) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Turnover);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasId) {
        output.WriteRawTag(8);
        output.WriteUInt64(Id);
      }
      if (HasSecurityId) {
        output.WriteRawTag(16);
        output.WriteUInt64(SecurityId);
      }
      if (HasSymbol) {
        output.WriteRawTag(26);
        output.WriteString(Symbol);
      }
      if (HasTimeFrame) {
        output.WriteRawTag(32);
        output.WriteEnum((int) TimeFrame);
      }
      if (time_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Time);
      }
      if (HasOpen) {
        output.WriteRawTag(81);
        output.WriteDouble(Open);
      }
      if (HasHigh) {
        output.WriteRawTag(89);
        output.WriteDouble(High);
      }
      if (HasLow) {
        output.WriteRawTag(97);
        output.WriteDouble(Low);
      }
      if (HasClose) {
        output.WriteRawTag(105);
        output.WriteDouble(Close);
      }
      if (HasPreclose) {
        output.WriteRawTag(113);
        output.WriteDouble(Preclose);
      }
      if (HasVolume) {
        output.WriteRawTag(121);
        output.WriteDouble(Volume);
      }
      if (HasTurnover) {
        output.WriteRawTag(129, 1);
        output.WriteDouble(Turnover);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasId) {
        output.WriteRawTag(8);
        output.WriteUInt64(Id);
      }
      if (HasSecurityId) {
        output.WriteRawTag(16);
        output.WriteUInt64(SecurityId);
      }
      if (HasSymbol) {
        output.WriteRawTag(26);
        output.WriteString(Symbol);
      }
      if (HasTimeFrame) {
        output.WriteRawTag(32);
        output.WriteEnum((int) TimeFrame);
      }
      if (time_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Time);
      }
      if (HasOpen) {
        output.WriteRawTag(81);
        output.WriteDouble(Open);
      }
      if (HasHigh) {
        output.WriteRawTag(89);
        output.WriteDouble(High);
      }
      if (HasLow) {
        output.WriteRawTag(97);
        output.WriteDouble(Low);
      }
      if (HasClose) {
        output.WriteRawTag(105);
        output.WriteDouble(Close);
      }
      if (HasPreclose) {
        output.WriteRawTag(113);
        output.WriteDouble(Preclose);
      }
      if (HasVolume) {
        output.WriteRawTag(121);
        output.WriteDouble(Volume);
      }
      if (HasTurnover) {
        output.WriteRawTag(129, 1);
        output.WriteDouble(Turnover);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Id);
      }
      if (HasSecurityId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(SecurityId);
      }
      if (HasSymbol) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Symbol);
      }
      if (HasTimeFrame) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TimeFrame);
      }
      if (time_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Time);
      }
      if (HasOpen) {
        size += 1 + 8;
      }
      if (HasHigh) {
        size += 1 + 8;
      }
      if (HasLow) {
        size += 1 + 8;
      }
      if (HasClose) {
        size += 1 + 8;
      }
      if (HasPreclose) {
        size += 1 + 8;
      }
      if (HasVolume) {
        size += 1 + 8;
      }
      if (HasTurnover) {
        size += 2 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BarDM other) {
      if (other == null) {
        return;
      }
      if (other.HasId) {
        Id = other.Id;
      }
      if (other.HasSecurityId) {
        SecurityId = other.SecurityId;
      }
      if (other.HasSymbol) {
        Symbol = other.Symbol;
      }
      if (other.HasTimeFrame) {
        TimeFrame = other.TimeFrame;
      }
      if (other.time_ != null) {
        if (time_ == null) {
          Time = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Time.MergeFrom(other.Time);
      }
      if (other.HasOpen) {
        Open = other.Open;
      }
      if (other.HasHigh) {
        High = other.High;
      }
      if (other.HasLow) {
        Low = other.Low;
      }
      if (other.HasClose) {
        Close = other.Close;
      }
      if (other.HasPreclose) {
        Preclose = other.Preclose;
      }
      if (other.HasVolume) {
        Volume = other.Volume;
      }
      if (other.HasTurnover) {
        Turnover = other.Turnover;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadUInt64();
            break;
          }
          case 16: {
            SecurityId = input.ReadUInt64();
            break;
          }
          case 26: {
            Symbol = input.ReadString();
            break;
          }
          case 32: {
            TimeFrame = (global::DataModel.ETimeFrame) input.ReadEnum();
            break;
          }
          case 42: {
            if (time_ == null) {
              Time = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Time);
            break;
          }
          case 81: {
            Open = input.ReadDouble();
            break;
          }
          case 89: {
            High = input.ReadDouble();
            break;
          }
          case 97: {
            Low = input.ReadDouble();
            break;
          }
          case 105: {
            Close = input.ReadDouble();
            break;
          }
          case 113: {
            Preclose = input.ReadDouble();
            break;
          }
          case 121: {
            Volume = input.ReadDouble();
            break;
          }
          case 129: {
            Turnover = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadUInt64();
            break;
          }
          case 16: {
            SecurityId = input.ReadUInt64();
            break;
          }
          case 26: {
            Symbol = input.ReadString();
            break;
          }
          case 32: {
            TimeFrame = (global::DataModel.ETimeFrame) input.ReadEnum();
            break;
          }
          case 42: {
            if (time_ == null) {
              Time = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Time);
            break;
          }
          case 81: {
            Open = input.ReadDouble();
            break;
          }
          case 89: {
            High = input.ReadDouble();
            break;
          }
          case 97: {
            Low = input.ReadDouble();
            break;
          }
          case 105: {
            Close = input.ReadDouble();
            break;
          }
          case 113: {
            Preclose = input.ReadDouble();
            break;
          }
          case 121: {
            Volume = input.ReadDouble();
            break;
          }
          case 129: {
            Turnover = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
